from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from datagenerate import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1600, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1600, 900))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        MainWindow.setFont(font)
        icon = QtGui.QIcon.fromTheme("accessories-dictionary")
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.settings_1 = QtWidgets.QLabel(self.centralwidget)
        self.settings_1.setGeometry(QtCore.QRect(40, 270, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        self.settings_1.setFont(font)
        self.settings_1.setStyleSheet("text-decoration: underline;\n"
        "font: 700 12pt \"Corbel\";")
        self.settings_1.setObjectName("settings_1")
        # Create a QTextBrowser widget for rx
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 1501, 91))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("font: 700 12pt \"Corbel\";")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setTabChangesFocus(True)
        # rx received data
        self.textBrowser.setObjectName("textBrowser")
        self.rx = QtWidgets.QLabel(self.centralwidget)
        self.rx.setGeometry(QtCore.QRect(30, 130, 451, 20))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.rx.setFont(font)
        self.rx.setObjectName("rx")
        # tx received data
        self.tx = QtWidgets.QLabel(self.centralwidget)
        self.tx.setGeometry(QtCore.QRect(30, 0, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.tx.setFont(font)
        self.tx.setObjectName("tx")
        #Create a TextBrowser for tx   
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 170, 1501, 91))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("font: 700 12pt \"Corbel\";")
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textBrowser_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_2.setTabChangesFocus(True)
        self.textBrowser_2.setObjectName("textBrowser_2")
        
        
        #port side
        self.port = QtWidgets.QLabel(self.centralwidget)
        self.port.setGeometry(QtCore.QRect(60, 640, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.port.setFont(font)
        self.port.setObjectName("port")
        self.port_box = QtWidgets.QComboBox(self.centralwidget)
        self.port_box.setGeometry(QtCore.QRect(110, 640, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.port_box.setFont(font)
        self.port_box.setObjectName("port_box")
        self.baudrate_box = QtWidgets.QComboBox(self.centralwidget)
        self.baudrate_box.setGeometry(QtCore.QRect(110, 680, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.baudrate_box.setFont(font)
        self.baudrate_box.setObjectName("baudrate_box")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.baudrate_box.addItem("")
        self.databits = QtWidgets.QLabel(self.centralwidget)
        self.databits.setGeometry(QtCore.QRect(30, 720, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.databits.setFont(font)
        self.databits.setObjectName("databits")
        self.databits_box = QtWidgets.QComboBox(self.centralwidget)
        self.databits_box.setGeometry(QtCore.QRect(110, 720, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.databits_box.setFont(font)
        self.databits_box.setObjectName("databits_box")
        self.databits_box.addItem("")
        self.databits_box.addItem("")
        self.databits_box.addItem("")
        self.databits_box.addItem("")
        self.baudrate = QtWidgets.QLabel(self.centralwidget)
        self.baudrate.setGeometry(QtCore.QRect(20, 680, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.baudrate.setFont(font)
        self.baudrate.setObjectName("baudrate")
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.setGeometry(QtCore.QRect(430, 770, 151, 29))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.connect_button.setFont(font)
        self.connect_button.setAcceptDrops(False)
        self.connect_button.setCheckable(True)
        self.connect_button.setChecked(True)
        self.connect_button.setAutoDefault(False)
        self.connect_button.setDefault(False)
        self.connect_button.setFlat(False)
        self.connect_button.setObjectName("connect_button")
        self.stopbits = QtWidgets.QLabel(self.centralwidget)
        self.stopbits.setGeometry(QtCore.QRect(350, 680, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.stopbits.setFont(font)
        self.stopbits.setObjectName("stopbits")
        self.flow_box = QtWidgets.QComboBox(self.centralwidget)
        self.flow_box.setGeometry(QtCore.QRect(430, 720, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.flow_box.setFont(font)
        self.flow_box.setObjectName("flow_box")
        self.flow_box.addItem("")
        self.flow_box.addItem("")
        self.stopbit_box = QtWidgets.QComboBox(self.centralwidget)
        self.stopbit_box.setGeometry(QtCore.QRect(430, 680, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.stopbit_box.setFont(font)
        self.stopbit_box.setObjectName("stopbit_box")
        self.stopbit_box.addItem("")
        self.stopbit_box.addItem("")
        self.stopbit_box.addItem("")
        self.flowcontrol = QtWidgets.QLabel(self.centralwidget)
        self.flowcontrol.setGeometry(QtCore.QRect(320, 720, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.flowcontrol.setFont(font)
        self.flowcontrol.setObjectName("flowcontrol")
        self.parity_box = QtWidgets.QComboBox(self.centralwidget)
        self.parity_box.setGeometry(QtCore.QRect(430, 640, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.parity_box.setFont(font)
        self.parity_box.setObjectName("parity_box")
        self.parity_box.addItem("")
        self.parity_box.addItem("")
        self.parity_box.addItem("")
        self.parity_box.addItem("")
        self.parity = QtWidgets.QLabel(self.centralwidget)
        self.parity.setGeometry(QtCore.QRect(360, 640, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.parity.setFont(font)
        self.parity.setObjectName("parity")
        self.generateBtn = QtWidgets.QPushButton("Generate Data",self.centralwidget)
        self.generateBtn.setGeometry(QtCore.QRect(450, 290, 91, 31))

        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.generateBtn.setFont(font)
        self.generateBtn.setStyleSheet("font: 700 10pt \"Corbel\";")
        self.generateBtn.setObjectName("generateBtn")
        #function lists

        self.functionList = QtWidgets.QListWidget(self.centralwidget)
        self.functionList.setGeometry(QtCore.QRect(40, 370, 231, 121))
        self.functionList.setObjectName("functionList")
        item = QtWidgets.QListWidgetItem()
        self.functionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.functionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.functionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.functionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.functionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.functionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.functionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.functionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.functionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.functionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.functionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.functionList.addItem(item)
        self.settings_2 = QtWidgets.QLabel(self.centralwidget)
        self.settings_2.setGeometry(QtCore.QRect(100, 340, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        self.settings_2.setFont(font)
        self.settings_2.setStyleSheet("text-decoration: underline;\n"
        "font: 700 12pt \"Corbel\";")
        self.settings_2.setObjectName("settings_2")
        self.generateDataBtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.generateDataBtn_2.setGeometry(QtCore.QRect(70, 500, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.generateDataBtn_2.setFont(font)
        self.generateDataBtn_2.setStyleSheet("font: 700 9pt \"Corbel\";")
        self.generateDataBtn_2.setObjectName("generateDataBtn_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(40, 580, 431, 51))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.settings_3 = QtWidgets.QLabel(self.centralwidget)
        self.settings_3.setGeometry(QtCore.QRect(380, 340, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        self.settings_3.setFont(font)
        self.settings_3.setStyleSheet("text-decoration: underline;\n"
        "font: 700 12pt \"Corbel\";")
        self.settings_3.setObjectName("settings_3")
        self.generateDataBtn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.generateDataBtn_3.setGeometry(QtCore.QRect(70, 530, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.generateDataBtn_3.setFont(font)
        self.generateDataBtn_3.setStyleSheet("font: 700 9pt \"Corbel\";")
        self.generateDataBtn_3.setObjectName("generateDataBtn_3")
        self.generateDataBtn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.generateDataBtn_4.setGeometry(QtCore.QRect(140, 500, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.generateDataBtn_4.setFont(font)
        self.generateDataBtn_4.setStyleSheet("font: 700 9pt \"Corbel\";")
        self.generateDataBtn_4.setObjectName("generateDataBtn_4")
        self.generateDataBtn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.generateDataBtn_5.setGeometry(QtCore.QRect(140, 530, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.generateDataBtn_5.setFont(font)
        self.generateDataBtn_5.setStyleSheet("font: 700 9pt \"Corbel\";")
        self.generateDataBtn_5.setObjectName("generateDataBtn_5")
        self.nofity_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.nofity_2.setGeometry(QtCore.QRect(280, 370, 271, 121))
        self.nofity_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.nofity_2.setObjectName("nofity_2")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(110, 280, 331, 51))
        self.textBrowser_4.setObjectName("textBrowser_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuToolBar = QtWidgets.QMenu(self.menuEdit)
        self.menuToolBar.setObjectName("menuToolBar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setCheckable(False)
        self.actionSave.setEnabled(True)
        self.actionSave.setObjectName("actionSave")
        self.actionNew_File = QtWidgets.QAction(MainWindow)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        self.actionTutorial.setObjectName("actionTutorial")
        self.actionSend_Dialog = QtWidgets.QAction(MainWindow)
        self.actionSend_Dialog.setCheckable(True)
        self.actionSend_Dialog.setObjectName("actionSend_Dialog")
        self.actionStandard_Configuration = QtWidgets.QAction(MainWindow)
        self.actionStandard_Configuration.setCheckable(True)
        self.actionStandard_Configuration.setObjectName("actionStandard_Configuration")
        self.actionCustomize = QtWidgets.QAction(MainWindow)
        self.actionCustomize.setObjectName("actionCustomize")
        self.actionPrefences = QtWidgets.QAction(MainWindow)
        self.actionPrefences.setObjectName("actionPrefences")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionClosed_Session = QtWidgets.QAction(MainWindow)
        self.actionClosed_Session.setObjectName("actionClosed_Session")
        self.actionSave_Session = QtWidgets.QAction(MainWindow)
        self.actionSave_Session.setObjectName("actionSave_Session")
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClosed_Session)
        self.menuFile.addAction(self.actionSave_Session)
        self.menuFile.addAction(self.actionPrefences)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuToolBar.addSeparator()
        self.menuToolBar.addAction(self.actionStandard_Configuration)
        self.menuToolBar.addAction(self.actionCustomize)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuToolBar.menuAction())
        self.menuEdit.addAction(self.actionSend_Dialog)
        self.menuSettings.addAction(self.actionTutorial)
        self.menuSettings.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
          
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.settings_1.setText(_translate("MainWindow", "Settings"))
        self.rx.setText(_translate("MainWindow", "RX ( Received Data) - Terminal View"))
        self.tx.setText(_translate("MainWindow", "TX ( Transmit Data)"))
        self.port.setText(_translate("MainWindow", "Port"))
        self.baudrate_box.setItemText(0, _translate("MainWindow", "110"))
        self.baudrate_box.setItemText(1, _translate("MainWindow", "300"))
        self.baudrate_box.setItemText(2, _translate("MainWindow", "600"))
        self.baudrate_box.setItemText(3, _translate("MainWindow", "1200"))
        self.baudrate_box.setItemText(4, _translate("MainWindow", "2400"))
        self.baudrate_box.setItemText(5, _translate("MainWindow", "4800"))
        self.baudrate_box.setItemText(6, _translate("MainWindow", "9600"))
        self.baudrate_box.setItemText(7, _translate("MainWindow", "14400"))
        self.baudrate_box.setItemText(8, _translate("MainWindow", "19200"))
        self.baudrate_box.setItemText(9, _translate("MainWindow", "38400"))
        self.baudrate_box.setItemText(10, _translate("MainWindow", "56000"))
        self.baudrate_box.setItemText(11, _translate("MainWindow", "57600"))
        self.baudrate_box.setItemText(12, _translate("MainWindow", "115200"))
        self.baudrate_box.setItemText(13, _translate("MainWindow", "128000"))
        self.baudrate_box.setItemText(14, _translate("MainWindow", "256000"))
        self.databits.setText(_translate("MainWindow", "Databits:"))
        self.databits_box.setItemText(0, _translate("MainWindow", "5 Databits"))
        self.databits_box.setItemText(1, _translate("MainWindow", "6 Databits"))
        self.databits_box.setItemText(2, _translate("MainWindow", "7 Databits"))
        self.databits_box.setItemText(3, _translate("MainWindow", "8 Databits"))
        self.baudrate.setText(_translate("MainWindow", "Baudrate:"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.stopbits.setText(_translate("MainWindow", "Stopbits:"))
        self.flow_box.setItemText(0, _translate("MainWindow", "Hardware"))
        self.flow_box.setItemText(1, _translate("MainWindow", "Xon/Xoff"))
        self.stopbit_box.setItemText(0, _translate("MainWindow", "1 stop bit"))
        self.stopbit_box.setItemText(1, _translate("MainWindow", "1,5 stop bit"))
        self.stopbit_box.setItemText(2, _translate("MainWindow", "2 stop bit"))
        self.flowcontrol.setText(_translate("MainWindow", "Flow Control:"))
        self.parity_box.setItemText(0, _translate("MainWindow", "Odd"))
        self.parity_box.setItemText(1, _translate("MainWindow", "Even"))
        self.parity_box.setItemText(2, _translate("MainWindow", "Mark"))
        self.parity_box.setItemText(3, _translate("MainWindow", "Space"))
        self.parity.setText(_translate("MainWindow", "Parity:"))
        self.generateBtn.setText(_translate("MainWindow", "Generate Data"))
        __sortingEnabled = self.functionList.isSortingEnabled()
        self.functionList.setSortingEnabled(False)
        item = self.functionList.item(0)
        item.setText(_translate("MainWindow", "CPSW Ethernet"))
        item = self.functionList.item(1)
        item.setText(_translate("MainWindow", "ICSSG Ethernet"))
        item = self.functionList.item(2)
        item.setText(_translate("MainWindow", "M.2 SSD"))
        item = self.functionList.item(3)
        item.setText(_translate("MainWindow", "M.CAN"))
        item = self.functionList.item(4)
        item.setText(_translate("MainWindow", "FINTEK F81604 CAN"))
        item = self.functionList.item(5)
        item.setText(_translate("MainWindow", " MCP2518 CAN"))
        item = self.functionList.item(6)
        item.setText(_translate("MainWindow", "FPGA"))
        item = self.functionList.item(7)
        item.setText(_translate("MainWindow", "Open GND IN/OUT"))
        item = self.functionList.item(8)
        item.setText(_translate("MainWindow", "MIL-STD-1553"))
        item = self.functionList.item(9)
        item.setText(_translate("MainWindow", "ARINC-429"))
        item = self.functionList.item(10)
        item.setText(_translate("MainWindow", "RS422"))
        item = self.functionList.item(11)
        item.setText(_translate("MainWindow", "USB Storage"))
        self.functionList.setSortingEnabled(__sortingEnabled)
        self.settings_2.setText(_translate("MainWindow", "Function Lists"))
        self.generateDataBtn_2.setText(_translate("MainWindow", "START"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "hr { height: 1px; border-width: 0; }\n"
        "li.unchecked::marker { content: \"\\2610\"; }\n"
        "li.checked::marker { content: \"\\2612\"; }\n"
        "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Corbel\'; font-size:12pt; font-weight:700;\">If serial port will be used;  the configuration can change in this section below.</span></p></body></html>"))
        self.settings_3.setText(_translate("MainWindow", "Error Details: "))
        self.generateDataBtn_3.setText(_translate("MainWindow", "RESUME"))
        self.generateDataBtn_4.setText(_translate("MainWindow", "STOP"))
        self.generateDataBtn_5.setText(_translate("MainWindow", "PAUSE"))
        self.nofity_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "hr { height: 1px; border-width: 0; }\n"
        "li.unchecked::marker { content: \"\\2610\"; }\n"
        "li.checked::marker { content: \"\\2612\"; }\n"
        "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
        "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "hr { height: 1px; border-width: 0; }\n"
        "li.unchecked::marker { content: \"\\2610\"; }\n"
        "li.checked::marker { content: \"\\2612\"; }\n"
        "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Corbel\'; font-size:10pt; font-weight:700; color:#000000;\">For genereta raw data, you can press the generate data button.</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "Session"))
        self.menuEdit.setTitle(_translate("MainWindow", "View"))
        self.menuToolBar.setTitle(_translate("MainWindow", "ToolBar"))
        self.menuSettings.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionSave.setText(_translate("MainWindow", "Open Session"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save a file."))
        self.actionNew_File.setText(_translate("MainWindow", "New Session"))
        self.actionNew_File.setStatusTip(_translate("MainWindow", "Create a new file"))
        self.actionAbout.setText(_translate("MainWindow", "About App"))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))
        self.actionSend_Dialog.setText(_translate("MainWindow", "Send Dialog Monitor"))
        self.actionStandard_Configuration.setText(_translate("MainWindow", "Standard Configuration"))
        self.actionCustomize.setText(_translate("MainWindow", "Customize"))
        self.actionPrefences.setText(_translate("MainWindow", "Prefences..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionClosed_Session.setText(_translate("MainWindow", "Closed Session"))
        self.actionSave_Session.setText(_translate("MainWindow", "Save Session"))


